FROM docker.io/golang:1.17.6-buster AS builder

RUN apt-get update
RUN apt-get install make git bash gcc
RUN mkdir -p /go/src/github.com/google
RUN git clone https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor

WORKDIR /go/src/github.com/google/cadvisor
RUN git fetch --tags
RUN git checkout {{_cadvisor_version}}
RUN make build
RUN cp ./cadvisor /

FROM docker.io/arm64v8/alpine:latest

RUN apk --no-cache add libc6-compat device-mapper findutils
RUN apk --no-cache add thin-provisioning-tools --repository http://dl-3.alpinelinux.org/alpine/edge/main/
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf
RUN rm -rf /var/cache/apk/*

COPY --from=builder /cadvisor /usr/bin/cadvisor

EXPOSE 8082

ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr", "-port=8082"]
