{
 "title": "Smartmeter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Elektriciteitsverbruik",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "afgelopen maand",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(gotsmart_active_power_delivered_l1_kw[30d])"
      }
     ]
    },
    {
     "title": "afgelopen maand",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(gotsmart_active_power_delivered_l1_kw[30d]) * 0.21"
      }
     ]
    },
    {
     "title": "huidige elektriciteitsverbruik kW",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "gotsmart_active_power_delivered_l1_kw"
      }
     ]
    },
    {
     "title": "elektriciteitsverbruik (KWh)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth" }
     ],
     "targets": [
      {
       "expr": "gotsmart_active_power_delivered_l1_kw * (2 - gotsmart_tariff_indicator_electricity)",
       "legendFormat": "dal uren"
      },
      {
       "expr": "gotsmart_active_power_delivered_l1_kw *(gotsmart_tariff_indicator_electricity-1)",
       "legendFormat": "nromale uren"
      }
     ]
    },
    {
     "title": "afgelopen week",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(gotsmart_active_power_delivered_l1_kw[1w])"
      }
     ]
    },
    {
     "title": "afgelopen week",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(gotsmart_active_power_delivered_l1_kw[1w]) * 0.21"
      }
     ]
    },
    {
     "title": "afgelopen 24h",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(gotsmart_active_power_delivered_l1_kw[24h])"
      }
     ]
    },
    {
     "title": "afgelopen 24h",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(gotsmart_active_power_delivered_l1_kw[1h]) * 0.21"
      }
     ]
    }
   ]
  },
  { "title": "Gasverbruik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "afgelopen maand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[30d])"
    }
   ]
  },
  {
   "title": "afgelopen maand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_active_power_delivered_l1_kw[30d]) * 0.667"
    }
   ]
  },
  {
   "title": "huidige gas verbruik m3",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(gotsmart_gas_usage_m3[60m])"
    }
   ]
  },
  {
   "title": "Gas verbruik m3/h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "expr": "rate(gotsmart_gas_usage_m3[60m])",
     "legendFormat": "verbruik per uur"
    }
   ]
  },
  {
   "title": "afgelopen week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[7d])"
    }
   ]
  },
  {
   "title": "afgelopen week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_active_power_delivered_l1_kw[7d]) * 0.667"
    }
   ]
  },
  {
   "title": "afgelopen 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[24h])"
    }
   ]
  },
  {
   "title": "afgelopen 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_active_power_delivered_l1_kw[1d]) * 0.667"
    }
   ]
  },
  { "title": "Spanning en Stroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "gotsmart_voltage_V", "legendFormat": "net spanning" }
   ]
  },
  {
   "title": "Stroom",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "gotsmart_current_l1_a", "legendFormat": "net spanning" }
   ]
  },
  { "title": "Stroom storingen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "langdurige stroomstoringen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gotsmart_long_power_failures_total",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "totaal aantal stroomstoringen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gotsmart_power_failures_total", "legendFormat": "Consumption" }
   ]
  },
  {
   "title": "spanning dips",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gotsmart_voltage_sags_in_phase_l1_total",
     "legendFormat": "Consumption"
    }
   ]
  }
 ]
}