{
 "title": "HAProxy 2 Full",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "backend", "label": "Backend", "query": { "query": "label_values(backend)" } },
   { "name": "frontend", "label": "Frontend", "query": { "query": "label_values(frontend)" } },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total,code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All HTTP responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }} "
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\"}[$__rate_interval])) by (code)",
     "legendFormat": "Back {{ code }}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{backend=~\"$backend\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{backend=~\"$backend\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{frontend=~\"$frontend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{backend=~\"$backend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "Requests and Responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front requests"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front requests errors"
    },
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front request denied"
    },
    {
     "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back redispatch warnings"
    },
    {
     "expr": "sum(rate(haproxy_backend_retry_warnings_total{backend=~\"$backend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back retry warnings"
    },
    {
     "expr": "sum(rate(haproxy_backend_response_errors_total{backend=~\"$backend\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back response errors"
    },
    {
     "expr": "sum(haproxy_backend_current_queue{backend=~\"$backend\"}) by (instance)",
     "legendFormat": "Back queued requests"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back requests"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\"}) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{frontend=~\"$frontend\"}) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  { "title": "Throughtput / Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Front - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\"}[$__rate_interval])*8",
     "legendFormat": "IN  "
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\"}[$__rate_interval])*8",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Back - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{backend=~\"$backend\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{backend=~\"$backend\"}[$__rate_interval])*8",
     "legendFormat": "OUT {{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - Connections successful / denied",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "- denied / + successful" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{frontend=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "Successful {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_denied_connections_total{frontend=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "Denied {{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Connections attempts / errors",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "- error / + attempt" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_connection_attempts_total{backend=~\"$backend\"}[$__rate_interval])",
     "legendFormat": "Attempts {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_connection_errors_total{backend=~\"$backend\"}[$__rate_interval])",
     "legendFormat": "Error {{ proxy }}"
    }
   ]
  },
  { "title": "Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Front - HTTP requests OK / Error / Denied",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "- error - denied / + ok" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "Total {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "Error {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "Denied {{ proxy }}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Back - Avg connection time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_connect_time_average_seconds{backend=~\"$backend\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Back - Avg response time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_response_time_average_seconds{backend=~\"$backend\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Avg. total time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_total_time_average_seconds{backend=~\"$backend\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  }
 ]
}