{
 "title": "mysportsplanner",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dag",
    "label": "dag",
    "query": {
     "query": "label_values(mysportplanner_schedule,event_day)"
    }
   },
   {
    "name": "training",
    "label": "training",
    "query": {
     "query": "label_values(mysportplanner_schedule{event_day=~\"$dag\"},event_activity)"
    }
   },
   {
    "name": "yyyy",
    "label": "yyyy",
    "query": {
     "query": "label_values(mysportplanner_schedule{event_day=~\"$dag\",event_activity=\"$training\"},event_date)"
    }
   },
   {
    "name": "mm",
    "label": "mm",
    "query": {
     "query": "label_values(mysportplanner_schedule{event_day=~\"$dag\",event_activity=\"$training\",event_date=~\".*-.*-$yyyy\"},event_date)"
    }
   },
   {
    "name": "dd",
    "label": "dd",
    "query": {
     "query": "label_values(mysportplanner_schedule{event_day=~\"$dag\",event_activity=\"$training\",event_date=~\".*-$mm-$yyyy\"},event_date)"
    }
   },
   {
    "name": "tijd",
    "label": "tijd",
    "query": {
     "query": "label_values(mysportplanner_schedule{event_day=~\"$dag\",event_activity=\"$training\",event_date=~\".*-$mm-$yyyy\"},event_time)"
    }
   },
   {
    "name": "team",
    "label": "team",
    "query": {
     "query": "label_values(mysportplanner_schedule,member_team)"
    }
   },
   {
    "name": "naam",
    "label": "naam",
    "query": {
     "query": "label_values(mysportplanner_schedule{member_team=\"$team\"},member_full_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Planning   $dag   $dd-$mm-$yyyy   $training  $tijd - aanwezig",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysportplanner_schedule{presence=\"aanwezig\",event_date=\"$dd-$mm-$yyyy\",event_activity=\"$training\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Planning   $dag   $dd-$mm-$yyyy   $training  $tijd - afwezig",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "mysportplanner_schedule{presence=\"afwezig\",event_date=\"$dd-$mm-$yyyy\",event_activity=\"$training\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Planning   $dag   $dd-$mm-$yyyy   $training  $tijd - niet gepland",
   "type": "table",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "mysportplanner_schedule{presence=\"niet gepland\",event_date=\"$dd-$mm-$yyyy\",event_activity=\"$training\",member_team=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$team",
   "type": "table",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "mysportplanner_schedule{member_team=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}