{
 "title": "Karma",
 "description": "Get started faster with Grafana Cloud then easily build these dashboards. https://grafana.com/products/cloud/\nOverview of metrics from Prometheus 2.0.  \nUseful for using prometheus to monitor your prometheus.\nRevisions welcome!",
 "tags": [ "prometheus" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  { "title": "at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime [$interval]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(karma_alertmanager_up[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Currently Up",
   "type": "table-old",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"karma\"}"
    }
   ]
  },
  {
   "title": "Total collect cycles",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karma_collect_cycles_total{instance=\"dsm:8081\"}"
    }
   ]
  },
  {
   "title": "Alert manager errors - alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karma_alertmanager_errors_total{instance=\"dsm:8081\",endpoint=\"alerts\"}"
    }
   ]
  },
  {
   "title": "Alert manager errors - silences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karma_alertmanager_errors_total{instance=\"dsm:8081\",endpoint=\"silences\"}"
    }
   ]
  },
  { "title": "counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "collected alert counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "counts" }
   ],
   "targets": [
    {
     "expr": "karma_collected_alerts_count{alertmanager=\"local\",instance=\"dsm:8081\",job=\"karma\",receiver=\"global\",state=\"active\"}",
     "legendFormat": "active"
    },
    {
     "expr": "karma_collected_alerts_count{alertmanager=\"local\",instance=\"dsm:8081\",job=\"karma\",receiver=\"global\",state=\"suppressed\"}",
     "legendFormat": "suppressed"
    },
    {
     "expr": "karma_collected_alerts_count{alertmanager=\"local\",instance=\"dsm:8081\",job=\"karma\",receiver=\"global\",state=\"unprocessed\"}",
     "legendFormat": "unprocessed"
    }
   ]
  },
  {
   "title": "collected alert counts groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "counts" }
   ],
   "targets": [
    {
     "expr": "karma_collected_groups_count{alertmanager=\"local\",instance=\"dsm:8081\",job=\"karma\",receiver=\"global\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}