{
 "title": "P2000",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "label": "type", "query": { "query": "label_values(description)" } },
   { "name": "prio", "label": "prio", "query": { "query": "label_values(title)" } }
  ]
 },
 "panels": [
  {
   "title": "seconds since events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "p2000_seconds_since_event{description=~\"$type.*\",title=~\"$prio.*\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "scrape counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "p2000_scrape_counter" }
   ]
  },
  {
   "title": "scrape response time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "p2000_scrape_response_time_seconds{status=\"200\"}",
     "legendFormat": "http_code = 200"
    },
    {
     "expr": "p2000_scrape_response_time_seconds{status!~\"200\"}",
     "legendFormat": "http_code != 200"
    }
   ]
  },
  {
   "title": "event counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "p2000_event_counter" }
   ]
  },
  {
   "title": "scrape response size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "p2000_scrape_response_size_bytes"
    }
   ]
  }
 ]
}