groups:
    - name: p2000.rules
      rules:
      - alert: p2000-down
        annotations:
          description: 'p2000-exporter is down {{ $labels.instance }}'
          summary: 'p2000-exporter is down'
        expr: up{job="p2000-exporter"} != 1 or absent(up{job="p2000-exporter"}) ==1
        for: 1m
        labels:
          severity: critical
          repeat_interval: 1h
      - alert: brandweeralarm
        annotations:
          description: '{{ $labels.pubdate }}: {{ $labels.description }} - {{ $labels.title }} - {{ $labels.link }}'
          summary: 'p2000 is down'
        expr: p2000_seconds_since_event{title=~"P_.*",description=~"Brandweer.*"} > -36000 AND p2000_seconds_since_event{title=~"P_.*",description=~"Brandweer.*"} < 36000
        for: 1m
        labels:
          severity: informational
          repeat_interval: 1h
      - alert: politie
        annotations:
          description: '{{ $labels.pubdate }}: {{ $labels.description }} - {{ $labels.title }} - {{ $labels.link }}'
          summary: 'p2000 is down'
        expr: p2000_seconds_since_event{description=~"Politie.*"} > -36000 AND p2000_seconds_since_event{description=~"Politie.*"} < 36000
        for: 1m
        labels:
          severity: informational
          repeat_interval: 1h
      - alert: ambulance
        annotations:
          description: '{{ $labels.pubdate }}: {{ $labels.description }} - {{ $labels.title }} - {{ $labels.link }}'
          summary: 'p2000 is down'
        expr: p2000_seconds_since_event{title=~"A[0-9]_.*",description=~"Ambulance.*"} > -36000 AND p2000_seconds_since_event{title=~"A[0-9]_.*",description=~"Ambulannce.*"} < 36000
        for: 1m
        labels:
          severity: informational
          repeat_interval: 1h