groups:
    - name: grafana.rules
      rules:
      - alert: grafana-down
        annotations:
          description: 'grafana is down {{ $labels.instance }}'
          summary: 'grafana is down'
        expr: up{job="grafana"} != 1 or absent(up{job="grafana"}) ==1
        for: 1m
        labels:
          severity: critical
          repeat_interval: 1h
