groups:
    - name: karma.rules
      rules:
      - alert: karma-down
        annotations:
          description: 'karma is down {{ $labels.instance }}'
          summary: 'karma is down'
        expr: up{job="karma"} != 1 or absent(up{job="karma"}) ==1
        for: 1m
        labels:
          severity: critical
          repeat_interval: 1h
