groups:
    - name: p2000.rules
      rules:
      - alert: p2000-down
        annotations:
          description: 'p2000 is down {{ $labels.instance }}'
          summary: 'p2000 is down'
        expr: up{job="p2000"} != 1 or absent(up{job="p2000"}) ==1
        for: 1m
        labels:
          severity: critical
          repeat_interval: 1h
      - alert: brandweeralarm
        annotations:
          description: '{{ $labels.pubdate }}: {{ $labels.description }} - {{ $labels.title }} - {{ $labels.link }}'
          summary: 'p2000 is down'
        expr: p2000_seconds_since_event{title=~"P_.*",description=~"Brandweer.*"} > 0 AND p2000_seconds_since_event{title=~"P_.*",description=~"Brandweer.*"} < 36000
        for: 1m
        labels:
          severity: critical
          repeat_interval: 1h