groups:
    - name: dsm.rules
      rules:
      - alert: dsm-exporter-down
        annotations:
          description: 'dsm-exporter is down {{ $labels.instance }}'
          summary: 'dsm-exporter is down'
        expr: up{job="dsm-exporter"} != 1 or absent(up{job="dsm-exporter"}) ==1
        for: 1m
        labels:
          severity: critical
          repeat_interval: 1h
      - alert: Gasgebruik_0-5
        expr: delta(gotsmart_gas_usage_m3[10m])>0.01  and ON() hour() > 0 < 5
        for: 10m
        labels:
          severity: warning
          repeat_interval: 1h
        annotations:
          summary: 'Gasgebruik tussen 0:00 en 5:00'
          description: 'Gasgebruik tussen 0:00 en 5:00 maar dan 0.1m3'
      - alert: Elektriciteitsbruik_0-5
        expr: gotsmart_active_power_delivered_l1_kw >0.4 and ON() hour() > 0 < 5
        for: 5m
        labels:
          severity: warning
          repeat_interval: 1h
        annotations:
          summary: 'Elektriciteitsbruik_0 tussen 0:00 en 5:00'
          description: 'Elektriciteitsbruik_0 tussen 0:00 en 5:00 maar dan 0.4kW'
