{
 "title": "Smartmeter",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Elektriciteitsverbruik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "afgelopen maand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_electricity_delivered_to_client_tariff_1_kwh[30d]) + delta(gotsmart_electricity_delivered_to_client_tariff_2_kwh[30d]) "
    }
   ]
  },
  {
   "title": "afgelopen maand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(gotsmart_electricity_delivered_to_client_tariff_1_kwh[30d]) + delta(gotsmart_electricity_delivered_to_client_tariff_2_kwh[30d])) * 0.21"
    }
   ]
  },
  {
   "title": "huidige elektriciteitsverbruik kW",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gotsmart_active_power_delivered_l1_kw"
    }
   ]
  },
  {
   "title": "elektriciteitsverbruik (KWh)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "gotsmart_active_power_delivered_l1_kw * (2 - gotsmart_tariff_indicator_electricity)",
     "legendFormat": "dal uren"
    },
    {
     "expr": "gotsmart_active_power_delivered_l1_kw *(gotsmart_tariff_indicator_electricity-1)",
     "legendFormat": "nromale uren"
    },
    {
     "expr": "avg_over_time(gotsmart_active_power_delivered_l1_kw[$__range])",
     "legendFormat": "gemiddelde"
    }
   ]
  },
  {
   "title": "afgelopen week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_electricity_delivered_to_client_tariff_1_kwh[1w]) + delta(gotsmart_electricity_delivered_to_client_tariff_2_kwh[1w]) "
    }
   ]
  },
  {
   "title": "afgelopen week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(gotsmart_electricity_delivered_to_client_tariff_1_kwh[1w]) + delta(gotsmart_electricity_delivered_to_client_tariff_2_kwh[1w])) * 0.21"
    }
   ]
  },
  {
   "title": "afgelopen 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_electricity_delivered_to_client_tariff_1_kwh[1d]) + delta(gotsmart_electricity_delivered_to_client_tariff_2_kwh[1d]) "
    }
   ]
  },
  {
   "title": "afgelopen 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(gotsmart_electricity_delivered_to_client_tariff_1_kwh[1d]) + delta(gotsmart_electricity_delivered_to_client_tariff_2_kwh[1d])) * 0.21"
    }
   ]
  },
  { "title": "Gasverbruik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "afgelopen maand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[30d])"
    }
   ]
  },
  {
   "title": "afgelopen maand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[30d]) * 0.667"
    }
   ]
  },
  {
   "title": "huidige gas verbruik m3/h",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[60m])"
    }
   ]
  },
  {
   "title": "Gas verbruik m3/h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "expr": "rate(gotsmart_gas_usage_m3[60m])",
     "legendFormat": "verbruik afgelopen uur"
    },
    {
     "expr": "rate(gotsmart_gas_usage_m3[1d])",
     "legendFormat": "verbuik afgelopen dag"
    },
    {
     "expr": "rate(gotsmart_gas_usage_m3[1w])",
     "legendFormat": "verbruik afgelopen week"
    }
   ]
  },
  {
   "title": "afgelopen week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[7d])"
    }
   ]
  },
  {
   "title": "afgelopen week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[7d]) * 0.667"
    }
   ]
  },
  {
   "title": "afgelopen 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[24h])"
    }
   ]
  },
  {
   "title": "afgelopen 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(gotsmart_gas_usage_m3[1d]) * 0.667"
    }
   ]
  },
  { "title": "Spanning en Stroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "gotsmart_voltage_V", "legendFormat": "net spanning" }
   ]
  },
  {
   "title": "Stroom",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "gotsmart_current_l1_a", "legendFormat": "net spanning" }
   ]
  },
  { "title": "Stroom storingen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "langdurige stroomstoringen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gotsmart_long_power_failures_total",
     "legendFormat": "verstoringen"
    }
   ]
  },
  {
   "title": "totaal aantal stroomstoringen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gotsmart_power_failures_total", "legendFormat": "verstoringen" }
   ]
  },
  {
   "title": "spanning dips",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gotsmart_voltage_sags_in_phase_l1_total",
     "legendFormat": "verstoringen"
    }
   ]
  }
 ]
}